### ISSUE TITLE
Wrong error reported in IDE on events?

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1056]
**Describe the bug**

Image is self explanatory:

![image](https://user-images.githubusercontent.com/2368384/107163033-59d87d80-69fb-11eb-9ca4-83bee52843a3.png)

Gives error on the line:

```java
this.module = module
```

but there is nothing wrong, and indeed it compiles well and no error is reported in Problems below.

**Expected behavior**

no error should be highlighted

**Screenshots**

**System configuration:**
-- SARL version: 0.11.0	
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [X ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	OpenJDK 11
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits

**Comment by ssardina** [comment]
BTW, I just realized that these inline fake errors are everywhere, for example:

![image](https://user-images.githubusercontent.com/2368384/107163069-986e3800-69fb-11eb-9881-6981b2153e55.png)

All those methods are defined and Java finds them and the system compiles well (no errors under Problems).

Maybe I have something wrongly configured in the IDE?

**Comment by ssardina** [comment]
ohhh OK, more info:

I closed the file, and then re-opened and all errors were gone!

So, not sure if you want to hunt this issue or is not worth it... If the latter, happy that you just close it.

**Comment by gallandarakhneorg** [comment]
Dear @ssardina.

There is some "stange behaviors" due to the Xtext framework on which the SARL compiler is based.
These errors may occur when we upgrade SARL because of the definition of a different version of SARL into the POM file than the version embedded in the Eclipse IDE (there is incompability between the class files from Xtext point of view), or because of several wrong references into the Eclipse workspace definition (sometimes Xtext seems to save error messages into a buffer of the Eclipse editor even if these errors are "temporary" in the compilation process). See Issue #1046 for this latest specific issue.

When upgrading, I recommend to:

* fix the SARL versions in the POM file in order to have the exact same versions as in the SARL IDE,
* do a full Maven compilation (on command-line if possible);
* and if the errors are still present, remove the project form Eclipse (without removing the code files), delete by hand the Eclipse project files (`.project`, `.classpath`, `.settings`), and import back the project into the Eclipse IDE, as a "SARL Maven project".
