### ISSUE TITLE
Compilation error creating custom space

### ISSUE THREAD

**Issue by xaviarias** [sarl/sarl#289]
Hello,

When I try to create a space I've defined in a Java class I get the following error:

ERROR:Type mismatch: cannot convert from Class<MySpaceSpecification> to Class<? extends SpaceSpecification<Space>> 

I'm using the following Maven dependencies:

           <dependency>
                <groupId>io.janusproject</groupId>
                <artifactId>io.janusproject.kernel</artifactId>
                <version>${janus.version.range}</version>
            </dependency>

     <janus.version.range>[2.0.2.0-SNAPSHOT, 2.0.3.0)</janus.version.range>

The way I create the space is based on the sarl-demo pingpong agents examples:

	on Initialize {
		defaultContext.createSpace(typeof(MySpaceSpecification), UUID::randomUUID) 
	}

And the Java code of the space classes is:

	public interface MySpaceSpecification extends SpaceSpecification<MySpace> {
	} 

	public class LDPlatformSpecificationImpl implements LDPlatformSpecification {
		@Override
		public MySpace create(SpaceID id, Object... params) {
			return new MySpace(id);
		}
	}

	public interface MySpace extends Space {
	}

	public class MySpaceImpl implements MySpace {
	}

Should I use XTend to define new spaces? The Java code of the space implementation uses Sarl agents, and agents depend on the custom space, so maybe there is an issue with the compilation dependencies?

**Comment by gallandarakhneorg** [comment]
Hello,

First, please check if you are using the latest SARL development environment. You should use the version 20150309050055 (released the 2015-03-09) or higher. Since Maven is downloading the latest development version, you must use the same version for the Eclipse product (that must be upgraded by hand).

I have coded your example in a fresh Maven project. I have some differences with your code example for ensuring to compile the Java code.
The code is available at: https://gist.github.com/gallandarakhneorg/bb1f1b03cbff58d057e5

Please get it, and compare to your own code.
If the issue still exists for you, is it possible to give an read access to your code? It may help for search the problem.

**Comment by xaviarias** [comment]
Hi Stéphane,

Thank for your reply, I've changed my project with your suggestions, actually my POM was a mess and now it looks much more simple.

About the code you have posted at Gist, it's very similar to mine except that the space implementation  refereces to an agent I've created. I guess this is a bad practice and it's better that spaces deal with agent's UUIDs. After changing this it's working fine, so I guess it was a matter of circular dependencies between SARL and Java.

In case you still want to investigate, my Eclipse Luna versions for SARL development kit are:

  SARL Development Kit	0.2.0.201503240406	io.sarl.sdk.feature.group	null
  SARL Language Definition	0.2.0.201503240406	io.sarl.lang.sdk.feature.group	null

Best regards
