### ISSUE TITLE
Install the SRE 

### ISSUE THREAD

**Issue by llin22** [sarl/sarl#318]
When I tried to set up the Run time environment in Eclipse, the following error appears:
Incompatible SRE with SARL 1.0.0.201508191412. Version must be lower than 0.3.0

Any clue? Thank you.

**Comment by ngaud** [comment]
Dear Llin22,

We encountered some problems with our continuous integration server and 
some corrupted archives were available for download for a short period, 
it could be the cause of your problem.
The problem is now solved, you can download the latest version of the 
complete SARL eclipse environmentfor your platform using the following 
link: http://www.sarl.io/download/index.html.

It is usually better to use the full eclipse version instead of 
installing SARL plugins in an existing eclipse installation, it reduces 
the risk of plugins versions incompatibility.

Thank for using SARL.

Nicolas.
on behalf of the SARL development team.

Le 19/08/2015 22:55, llin22 a écrit :
>
> When I tried to set up the Run time environment in Eclipse, the 
> following error appears:
> Incompatible SRE with SARL 1.0.0.201508191412. Version must be lower 
> than 0.3.0
>
> Any clue? Thank you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sarl/sarl/issues/318>.
>

-- 

*Dr. Nicolas GAUD*
/Associate Professor/
Multiagent Simulation Group

IRTES-SeT -- UTBM, EA 7274
Laboratoire Systèmes et Transport
Institut de Recherche sur les Transports, l’Énergie, et la Société
Université de Technologie de Belfort-Montbéliard
Rue Ernest Thierry-Mieg
90010 Belfort Cedex

Phone: (+33) [0]3 84 58 39 12
Cell: (+33) [0]6 75 99 25 53
Fax: (+33) [0]3 84 58 33 42
Skype: nicolas.gaud <skype:nicolas.gaud>
http://www.multiagent.fr/People:Gaud_nicolas 
<http://www.multiagent.fr/People:Gaud_nicolas>

<http://www.multiagent.fr> <http://www.utbm.fr/recherche/irtes.html>

**Comment by gallandarakhneorg** [comment]
This is a incompatibility between the Eclipse tools (version 1.0.0.x) and the Janus runtime environment (version 0.3.0). The Eclipse product provided on `sarl.io` is currently the "development" version. Consequently, you must use the "development version" of Janus as the runtime environment.

This issue related to download is specifically treated in #319.

**Comment by gallandarakhneorg** [comment]
FAQ was updated with this issue.
