### ISSUE TITLE
SARL in javascript/node.js

### ISSUE THREAD

**Issue by logixworx** [sarl/sarl#396]
How would I go about interfacing SARL with javascript or node.js? Thanks.

**Comment by gallandarakhneorg** [comment]
Interfacing SARL with Node.js is the same question as "interfacing a Java application to Node.js" since the SARL language is fully compatible with the Java libraries ([source](http://www.sarl.io/docs/suite/io/sarl/docs/reference/GeneralSyntaxReferenceSpec.html#Java_Interoperability)). 

For running Node.js in a Java run-time environment, I found [Nodyn](http://nodyn.io/). It permits to run node.js inside a JVM that could also run SARL agents.

The data connection between agents and node.js depends on what you want to do. You should indicate us how the SARL agents are supposed to be interfaced to the node.js framework.
