### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by dirkrathje** [sarl/sarl#407]
First of all, thank you so much! Your work is really inspiring. Congratulations. 

Sarl's meta model looks very mighty. I really like the abstraction of space as a common ground for interactions. But I wonder why I couldn't find anything like an abstraction of time. Have I overlooked this, or I am mistaken assuming this to be a limitation? Methodologically, I think Time is so an integral part of simulations (and for modeling in general) that it shouldn't be hidden in cycles of the run-time. And pragmatically, how to deal with the situation when a model turns out to be in need of parts for which shorter cycles than the previous assumed one are crucial (e.g. a society is changing with a slower rate than the daily human life. And our lives are much slower than the chemical processing within us.): In that case any time reference in my model would have to be refactored, wouldn't it?

Best wishes,
Dirk

**Comment by gallandarakhneorg** [comment]
Dear Dirk.
You're right: Time is a key concept in a simulation platform.
However, SARL is not language specifically designed for simulation. It is also used by embedded and real-time applications in cyber-physical systems. That's we decided to not put a time concept in the metamodel of SARL. Indeed, the run model of the agents by the Janus platform (which run the SARL scripts) is fully parallel/distributed. It becomes difficult to include a generic time manager. We prefer to let the application developer to design its own time management or use the Java time objects, until now.

Nevertheless, since I'm using SARL for simulation, I have created an extension of the Janus platform (which is running the SARL scripts) with a time manager for simulation in discrete environments. You could take a look at (Jaak Time Manager)[https://github.com/gallandarakhneorg/jaak/blob/master/io.sarl.jaak.kernel/src/main/java/io/sarl/jaak/environment/external/time/TimeManager.java]. When I think this specific work is finished, and could be generic,  I will asked to publish it as a plugin of Janus and/or SARL. Consequently, you're welcome to comment this work.

@ngaud, @srodriguez, please put your comments related to the time management in this issue.

All the best.
Stéphane.

**Comment by dirkrathje** [comment]
Dear Stéphane, 

Thanks for your response. 
I will have a deeper look at Jaak and Janus then; though for my current objective it will not be necessary to adjust the time mechanics (I am trying to model some basic principles of economics,  psychology, and marketing communications for a class in business psychology; however I fear I am a bit naive about the workload. But you haven't understood the consequences of a principle if you haven't felt the pain of formally modeling it, have you? ;) I will keep you posted.

Best 
Dirk

**Comment by gallandarakhneorg** [comment]
Dear Dirk.
That's an interesting application. If putting timestamps in messages/events that are exchange by agents is enough for your application, you could do it in SARL with an attribute in an event. If you need to be sure that agents are evolving at the "same time" (quiet ambiguous notion here) then Jaak library may give you a starting point.
Please fill free to come back to us. We may collaborate together for helping you to build a nice SARL implementation of your model.
Regards,
Stéphane.

**Comment by dirkrathje** [comment]
Dear Stéphane, 

Sorry for the late reply. I am drowning in a pre-vacation workload tsunami right now (It's always the same ;)

Thank you so much for your offer. Would be great to collaborate. I hope I will have a project draft in a few weeks time (a part of my holidays is reserved for this.) I will love to come back to you then. 

Best,
Dirk

**Comment by gallandarakhneorg** [comment]
Dear @ngaud, @srodriguez 
.
We have a regression between Janus v1 and Janus v2 regarding the creation of simulators.
Indeed, it is hard to create a simulator with Janus v2 because there is no tool for controlling the time evolution during the simulation. I'm encountered big problems for creating simulator of daily negotations between 100,000 agents for transport trips. Time is important in the model. But it is difficult to ensure the simulation time evolution since every agent in running in parallel on the computer. 

My point of view is that the time manager must not coded at the SARL level because it is not the same level of abstraction. This is a typical simulator problem (according to Zeigler's relationships).

Consequently, at the SARL level, I propose to add only a new builtin capacity:
```
capacity Time {
   /* Replies the current time */
  def getTime : float

  /* Replies the current time in the given unit */
 def getTime(timeUnit : TimeUnit) : float

  /* Replies the scaling factor between the agent time and the operating system time.
     <p>os duration = OSTimeFactor * agent duraction */
 def getOSTimeFactor : float
}
```

Additionally, I propose to create an issue for creating a time manager in Janus.
Are you agree?

**Comment by gallandarakhneorg** [comment]
The management of simulated time will be considered in Issue #539.
