### ISSUE TITLE
Purge task launched by a behavior when unregistering this behavior

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#459]
_From @ngaud on November 11, 2014 13:54_

When a behavior is unregistered we currently do not stopped every tasks that have been launched by the corresponding behavior.

For doing that we must change the code generation to specify the initial launcher of a task, storing them in a map instead of a simple list and then killing them when unregistering the behavior.

_Copied from original issue: janus-project/janusproject#85_

**Comment by gallandarakhneorg** [comment]
This issue will be moved into the SARL project according to sarl/sarl#447.

**Comment by gallandarakhneorg** [comment]
My point of view is the following.

By default, tasks launched by a Behavior should be stopped when the behavior is unregistered. I think it will be easier for the developers to consider the Behavior's code as a standalone module.

We could update the Behaviors API in order to let the developer to specify the scope for running a task when launching it (need to refactor the Behaviors BIC). The scoping enumeration  may be.
```java
enum TaskRunScope {
    BEHAVIOR_SCOPE,
    AGENT_SCOPE,
}
```

Another approach, not my preferred one is to consider that all tasks are run with an agent scope. It applies only changes in the documentation.

What do you think?

**Comment by ngaud** [comment]
The scope is a good idea because the developers can choose. If you specify nothing it means you are by default in behavior scope, meaning the tasks will be killed when you unregister the behavior.

But from a model point of view considering a task as a basic behavioral building block that could be either associated to its launching behavior or to the default behavior of the agent. It means you introduce a distinction in terms of rights between behaviors launching task in its context and those launching tasks in the context of the agent. I consider that a task being part of the behavior an agent accept to commit to the behavior frame until it releases it. So introducing this distinction could be a problem in terms of behavior right management and associated commitment for the agent executing this behavior.

In a word, I think **we should not introduce the notion of scope**, and consider that every tasks launched by a behavior are BEHAVIOR_SCOPE and thus must be killed when you unrregister it.
And a warning could be raised when you unregister a behavior with currently running task that will be killed to inform the developer and help him to understand why these tasks has been killed.

**Comment by gallandarakhneorg** [comment]
Let purge the tasks that were launched by a behavior when this behavior is unregistered.
