### ISSUE TITLE
Eclipse sarl & GTK3

### ISSUE THREAD

**Issue by Lomadriel** [sarl/sarl#523]
Since the latest versions of GTK3, Eclipse doesn't work well.
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=492371

On Arch Linux it's a know bug, and the simplest solution is to force Eclipse to use GTK2.
You can either add
```
SWT_GTK3=0
```
before eclipse command, or modify eclipse.ini by adding
```
--launcher.GTK_version
2
```
before 
```
--launcher.appendVmargs
-vmargs
```

**Comment by gallandarakhneorg** [comment]
A launching script for Arch Linux will be added to the SARL product.
In the same direction as the discussion above, we could not force a specific GTK version in the SARL product because we have no control on the users' operating system, and the installed GTK version. Switching from GTK3 to GTK2 is still be a user choice.
