### ISSUE TITLE
Sarl.io in android

### ISSUE THREAD

**Issue by haidarknightfury** [sarl/sarl#530]
Hi,
   could you explain how to use sarl in android and android studio please

**Comment by gallandarakhneorg** [comment]
You must use a Eclipse distribution for using the SARL plugins. If your IDE is compatible, go on the download page of SARL, where the link to the update site that provides plugins is explained.

If you cannot do that, you could use the command-line compilers (on the download page too).

Keep in mind that the run-time environment of SARL (the SARL virtual machine) was not designed for being run on smartphones. You may encounter networking issues.

**Comment by gallandarakhneorg** [comment]
Regarding the support of Android Studio, the SARL tools cannot be using inside this environment because it is an extension of IntelliJ. The support of IntelliJ is not yet planned as explained in Issue #514.
As soon, the SARL development team is able to provide IntelliJ plugins, these plugins will be installable in Android studio.

**Comment by gallandarakhneorg** [comment]
This issue is a duplicate of #500.
