### ISSUE TITLE
Not enough AgentKilled occurrences after killMe() calls

### ISSUE THREAD

**Issue by GlennCich** [sarl/sarl#546]
I have the impression that when I call the killMe() function in an agent, something goes wrong.

I have one special agent which communicates with other normal agents. When I kill all the normal agents, I should expect that the AgentKilled event is received in the special agent as many times as the killMe() function is called, but this special agent only receives one AgentKilled event

Kind regards,
Glenn

**Comment by gallandarakhneorg** [comment]
I have added code for testing the number of `AgentKilled` occurrences that are received by a special agent.
The tests are successful for 100 agents.

Two explanations may considered:
* The issue is fixed between your version 0.3.x and the current version 0.5.x, because of the refactoring of the event dispatching algorithm.
* The special agent is not alive when a part of the other agents calls the killMe function.

**Comment by gallandarakhneorg** [comment]
May be solved by Issue #470.
