### ISSUE TITLE
General Syntax Reference 14.1 missing example

### ISSUE THREAD

**Issue by jgfoster** [sarl/sarl#547]
I'm trying to clean things up but I don't know enough about the syntax of the .spec file to fix this problem. The source appears to include sample code for "Import static extension methods", but I don't know how to get it to display.

**Comment by gallandarakhneorg** [comment]
Dear James.
You're right that the example is missed in the generated HTML pages. Even if the example exists in the Jnario specification.
Usually, the statement in the Java documentation `@filter(.* = '''|'''|.parseSuccessfully.*)` enables to filter the output of the code by displaying only the first parameter if the `parseSuccessfully` function.

The problem is caused by the two calls to the `parseSuccessfully` function. Indeed, the filtering is specified for matching `^[:CODE EXAMPLE:].parseSuccessfully[:IGNORED STRING:]$`. I propose to switched the two parts of the code in order to fit the filter specification:
```
			'''
			import static extension java.util.Collections.*
			agent A {
				def example {
					val colors : String[] = #["red", "blue", "green"]
					colors.sort // sort is implemented by Collections#sort(List<T>)
				}
			}
			'''.parseSuccessfully(
				"package io.sarl.docs.reference.gsr",
				// TEXT
				""
			)
                        //Verify if the example in section's introduction is true
			parseSuccessfully("
			package io.sarl.docs.reference.gsr
			class C1 {
				def removeVowels (s : String) {
					s.replaceAll(\"[aziouyAEIOUY]+\", \"\")
				}
				def caller1 {
					removeVowels(\"Hello\")
				}
				def caller2 {
					\"Hello\".removeVowels
				}
			}
			")
```

The first part is related to the "import static extension methods", and its example.
The second part is given for checking that the code example provided into the section's introduction is true. Indeed, there is no other place in the Jnario specification for testing the elements of a enclosing section.
