### ISSUE TITLE
Anonymous function not working

### ISSUE THREAD

**Issue by vivictor14** [sarl/sarl#655]
```
timer.schedule(new TimerTask() {
			override run {
				var data : String
				var tempBodies = new ArrayList<TestBody>
				data = reader.readLine()
				tempBodies = mapper.readValue(data, new TypeReference<ArrayList<TestBody>>() {})
				if(tempBodies.length > bodies.length) {
					emit(new InitAgents(tempBodies))
				} 
			}
		}, 0, 500)
```

`$CAPACITY_USE$IO_SARL_CORE_DEFAULTCONTEXTINTERACTIONS` cannot be resolved or is not a field

**Comment by gallandarakhneorg** [comment]
The `TimerTask` class is not a type that could be inferred to a Java lambda. It is inferred to a Java anonymous class. Because the access to the hidden capacity field is prefixed by `this.`, it tries to access to the anonymous class instance, but not the enclosing class instance.

Fix: prefix the hidden capacity use with a fully qualified name, e.g. `mypackage.MyType.this.`
