### ISSUE TITLE
No SARL libraries Nor Java libraries linked to a project created using existing code

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#675]
When I import a project using "Import existing projects into workspace" (with a directory containing SARL code), it creates a project without any SARL libraries in the project.

**Comment by gallandarakhneorg** [comment]
Cannot reproduce because:
* when there is neither `.classpath` nor `.project`, the wizard refused to continue.
* when there is `.classpath` and `.project`, the wizard uses the content of these files. No SARL specific configuration is applied.

If the issue is still valid, please provide a complete testing case (with the project folder content).
