### ISSUE TITLE
Redesign of the Janus architecture and re-implementation using SARL.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#751]
Janus may be rewritten in SARL. It should give an example of a complex application coded with SARL. At the same time, the Janus's implementation should be optimized.

**Comment by ssardina** [comment]
Hi @gallandarakhneorg . Not sure I understand this issue and proposed solution. Is this related to the issue we found in some machines when we somehow reach a limit on the events? 

I thought SARL ran on top of JANUS as underlying execution engine, are you proposing to get rid of Janus altogether? Sorry I must be missing something due to my lack of knowledge of SRI+Janus framework.

**Comment by gallandarakhneorg** [comment]
The new version of Janus is ready for review and tests. Except that the networking services are not yet implemented: I have decided to validate the implementation without adding the networking complexity for now.

**Comment by gallandarakhneorg** [comment]
The new implementation of Janus was renamed "Janus lite":  https://github.com/sarl/janus-lite

**Comment by gallandarakhneorg** [comment]
The SRE implementation written with the SARL language is renamed "Lite SRE".

It is designed for providing a faster framework than Janus.

It is accessed with: https://github.com/sarl/io.sarl.sre.lite

**Comment by gallandarakhneorg** [comment]
A extension of the "Lite SRE" that is dedicated to simulation application was started to be developped.

It provides specific scheduling and time management services.

It is accessible with: https://github.com/sarl/io.sarl.extensions.sre.simulation

**Comment by gallandarakhneorg** [comment]
This new version is in the branch `sgallandBranch`. It is considered as the next official version of the Janus platform (if it pass all the tests).
