### ISSUE TITLE
Spawn function first parameter strange behavior

### ISSUE THREAD

**Issue by je-patois** [sarl/sarl#794]
# Description
Given the following code:

```
agent Spawner {
	uses Logging, Lifecycle, InnerContextAccess

	on Initialize {
		info("Spawner started")
		loggingName = 'Spawner-' + this.ID
		spawnChildren()
	}
	
	def spawnChildren() {
		var ids : Iterable<UUID> = spawnInContext(3, typeof(Spawned), innerContext)
		
		ids.forEach[id : UUID |
			info(id)
		]
		
		info('There are ' + memberAgentCount + ' agents')
	}
}

agent Spawned {
	uses Logging

	on Initialize {
		loggingName = 'Spawned-' + this.ID
		info("Sub agent spawned with ID " + ID)
	}
}
```
The purpose is to make the `Spawner` agent spawn 3 `Spawned` agents at the same time, using the optional first parameter in the `spawn` or `spawnInContext` function.

# Problem
However, the result is not the one intended:
6 `Spawned` agents are actually created, with the `on Initialized` called 6 times.
Here are the related logs:

![bug 2](https://user-images.githubusercontent.com/26325774/34147413-e09167d8-e49d-11e7-96df-926f34c23a1e.png)

Apart from that problem, the function behaves as mentionned in issue #481: There is only one occurrence of the agent for a group of agents (`memberAgentCount` equals 1 when agents are spawned in context), but the returned `Iterable` var contains 3 same `UUID`, which doesn't seem to be intuitive. Returning a single `UUID` or allowing the agents to have different `UUID` could be an improvement.

# Tests
Here are the results for different values of the first parameter:
- 1 actually spawns 1 agent
- 2 spawns 3 agents
- 3 spawns 6 agents
- 4 spawns 10 agents
- ...

**Comment by gallandarakhneorg** [comment]
This issue is related to Issue #796.

**Comment by gallandarakhneorg** [comment]
The code of the `spawnChildren()` is invalid because the logged information should be most of the time wrong. Indeed the `spawnInContext` function creates the agents. But, when it returns, there is no warranty that all the spawned agents are created or initialized, due to the massive parallel mechanism of the run-time platform.
It is recommended to listen for `AgentSpawned`and `AgentKilled` for reacting to the real agents' creation.
The documentation of the spawning functions will be updated in order to be clear.

**Comment by gallandarakhneorg** [comment]
The returned values by `spawnInContext` are not valid. It is a bug within the agent injector.
