### ISSUE TITLE
debug() not working in Logging capactiy

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#803]
Hi,

I am using debug("xxxxxxx") from logging and even though I set log level above 4 nothing is printed.

setLogLevel(4)
if (isDebugLogEnabled) {
	System.out.println(logLevel)
}
debug("xxxxxxxxxxx")

4 is printed, but not xxxxxxxxx

info(), error() and warning() are working, but debug does not print anything:

Cheers and happy to do any test that is needed,

Sebastian

**Comment by gallandarakhneorg** [comment]
There is two levels of loggers in the current implementation of our framework:
1) the logger of the run-time environment, which is shared by all the agents, and
2) the logger associated to a single agent, which is child of the run-time environment's logger.

When you call `setLogLevel`, you change the logging level of the agent's logger (level 2). That's why `isDebugLogEnabled` replies `true`.

When `debug()` is called, after calling `isDebugLogEnabled` (level 2), it delegates the displaying of the message to the run-time environment's logger (level 1).
By default, the level-1 logger has the level `INFO`. That's why your debug messages are not displayed.

A quick fix is: By changing the level of the level-1 logger (with the command line option for example) you could enable the displaying of your debug message.

I will change the implementation of the logging system in order to let the level-2 logger managing the logging level. The command line configuration will correspond to the default configuration of an agent's logger. The level-1 logger will becomes an hidden logger that is not accessible.

**Comment by ssardina** [comment]
Thanks for that explanation, that explains it well.

I fully agree with your proposal, the level-2 agent logger should be managed by itself and apart form the system level 1 logger. (if I change the level-1 logger, I assume lots of other messages will pop out, which is not what I want)

I will leave my code as is as your proposed change will solve the issue well.
