### ISSUE TITLE
'final' error in generated Java

### ISSUE THREAD

**Issue by pinam45** [sarl/sarl#819]
#### Issue description

The following code does not compile:
```
agent Agent3 {
	uses Logging
	uses DefaultContextInteractions
	uses Lifecycle

	on Initialize {
		var id : UUID
		id = spawn(typeof(Agent2), "Gilbert")

		emit(new Hello, [it.UUID == id])
	}
}
```
Error:
```
Java problem: Local variable id defined in an enclosing scope must be final or effectively final
```
#### Additional details

- SARL version: 0.7.0
- Build id: 20180222144014 (2018-02-22)
- SARL compiler: Eclipse compiler without Maven
- Operating System: Windows 64bits

**Comment by gallandarakhneorg** [comment]
The issue comes from the Xbase compiler, which implicitly initializes the local variables with a default value. This initialization is invalid from the Java syntax point-of-view.

[Issue 237](https://github.com/eclipse/xtext-extras/issues/237) is reported within the Xtext project for opening the discussion and solving this problem.
