### ISSUE TITLE
Wrong Ambiguous binary operation error at CLI compile time (!= and .equals())

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#852]
**Describe the bug**

Wrong error at compile time when using (x != null) on ambiguous binary operation

**To Reproduce**

I have this code:

 ```
var car : Integer = kb_closestInactiveCar(occurrence.floor)
 if (car != null) {
               .............
          }
```

for which the CLI mvn compiler (not the ECLIPSE one) throws this error:

```
[ERROR] Ambiguous binary operation.
The operator declarations
 operator_notEquals(Integer, Long) in IntegerOperatorExtensions,
 operator_notEquals(Integer, Byte) in IntegerOperatorExtensions,
 operator_notEquals(Integer, Float) in IntegerOperatorExtensions,
 operator_notEquals(Integer, Integer) in IntegerOperatorExtensions,
 operator_notEquals(Integer, Double) in IntegerOperatorExtensions,
 operator_notEquals(Integer, Short) in IntegerOperatorExtensions,
 operator_notEquals(Integer, AtomicInteger) in IntegerOperatorExtensions and
 operator_notEquals(Integer, AtomicLong) in IntegerOperatorExtensions

```

**Expected behavior**

I don' t know but because the second parameter is "null", its type cannot be inferred. Then the SARL compiler cannot determine the right function "operator_notEquals" to call.

**System configuration:**
-- SARL version:	
-- SARL compiler:	
-  - [x] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	Sun 1.8
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by ssardina** [comment]
wow @gallandarakhneorg , you seems to have addressed all the issues I created! That is fantastic.

I guess all this will be in 0.8.0 version?

**Comment by gallandarakhneorg** [comment]
Please note that there is still an issue inside the Xbase library. Consider the two codes:
```sarl
def f(v : Integer) {
  if (v == null) {}
}
```
and
```sarl
def f(v : Integer) {
  if (null == v) {}
}
```

The first code compiles since my patch is applied.

The second code still causes an "ambiguous feature call" error because the linker provided by Xbase considers the type of the left-most argument for finding the functions to call. With a null value, all the types are possible. So that it is an ambiguous call.

**Comment by ssardina** [comment]
OK I see, but would it be best/safer to use if (nul === v)  {...} ?

**Comment by gallandarakhneorg** [comment]
Because the SARL `==` operator is mapped to the Java `equals()` function, and the `===` operator to the Java `==` operator, it is better/safer, and a best practice, to use `===` when one of the operands is of primitive type, e.g. null, number constants, primitive type variables.

Ususally, the SARL compiler generates a warning to push you to use `===` in place of `==`. But with `null==value`, an ambiguous call error occurs before the warning is generated.

I have created an issue regarding `null == value`: Issue #854. According to the associated discussion within the Xbase group [#300](https://github.com/eclipse/xtext-extras/issues/300), the error message will be updated to push the developers to use `===`.

**Comment by ssardina** [comment]
great work Stephane, thanks!

FYI, I am collecting these and other " common"  issues when doing SARL +
SWI + Maven for my course here:

https://bitbucket.org/snippets/ssardina/9er67X

Cheers

Sebastian

**Comment by gallandarakhneorg** [comment]
Very interesting FAQ. I propose to copy paste it into the official SARL FAQ. See Issue #855.

**Comment by ssardina** [comment]
Sure, go ahead. See my comment in that issue.
