### ISSUE TITLE
Agents communication enabled through space without being registered to it.

### ISSUE THREAD

**Issue by Valink** [sarl/sarl#934]
Ping and Pong agents are still able to communicate through a space even if they are not register in this particular space.
Agents are automatically added to a space when getOrCreate this space.

**To Reproduce**
- Download the following SARL sample : Help > Welcome > Sample > Ping pong in space.
- Comment `comspace.register(asEventListener())` in ping and/or pong agents.
For further explanations : valentin.sourice@utbm.fr

**Expected behavior**
Ping and Pong agents are not suppose to be able to (emit? and) receive events when not register in comspace.

**System configuration:**
-- SARL version: 0.9	
-- SARL compiler: 0.9
-  - [x] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name): 1.8
-- Operating System:	
-  - [ ] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [x] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits

**Comment by gallandarakhneorg** [comment]
This problem is fully reproductible in both 0.9 and 0.10 versions of SARL.

**Cause:** the function `getOrCreateSpaceWithSpec` is searching for a space instance that was created with an `OpenEventSpaceSpecification`. It is the case of the default space, which is implicitly created in all the agent contexts. Consequently the function `getOrCreateSpaceWithSpec` replies the default space and does not create a new space. Now, considering that all agents are implicitly registered to the default space, then it is normal that they receive the events (even if the `register` function is not invoked).

**Workaround:** None. A patch of the SARL run-time environment (SRE) is needed.

**Actions:**
1. Updating the documentation of `getOrCreateSpaceWithSpec` in order to indicate that the default space cannot be replied by this function.
2. Patching the SRE in order to fulfil the documentation.
3. Apply the same rules related to the default space to the other `getOrCreateSpace` and `getSpace` functions.
