### ISSUE TITLE
Why I am getting  Undefined agent io.sarl.airsim.BootAgent while trying to run the configuration

### ISSUE THREAD

**Issue by chachem97** [sarl/sarl#963]
Hello,

I have imported a project from github and cloned it into sarl.
While trying to run the configuration i am getting the following error:
 Undefined agent io.sarl.airsim.BootAgent

Can you please help me.

Regards,

Hachem

**Comment by gallandarakhneorg** [comment]
It means that the class `io.sarl.airsim.BootAgent` was not found in the classpath of your application.
Are you sure that all the Java classes are generated into your SARL project?

I may also recommend you to put an issue into the original repository in order to have the feedback of the original author of the airsim wrapper, i.e. @alexandrelombard.

**Comment by gallandarakhneorg** [comment]
Please follow the steps below:

- Install Maven as a command line tool
- Install Git as a command line tool
- type `cd RD` where `RD` is the directory in which the source code folders should be copied
- `git clone  https://github.com/alexandrelombard/airsim-jvm-api`
- `cd airsim-jvm-api`
- `./gladew build install`
- `cd ..`
- `git clone https://github.com/alexandrelombard/sarl-airsim-interface`
- cd `sarl-airsim-interface`
- `mvn clean install`

Everything should be compiled without error.

**Comment by gallandarakhneorg** [comment]
This issue seems not to be related to the code of SARL directly.
