### ISSUE TITLE
Interface between Sarl and Airsim

### ISSUE THREAD

**Issue by chachem97** [sarl/sarl#964]
Hello,

I am doing a project for controlling a drone in an environment. The drone will be moving in an environment and it will communicate with other components of this environment.
The code will be written in SARL and the simulation will be done in AirSim. 

Do we have an already implemented interface for the communication between Sarl And Airsim?

Regards.

**Comment by gallandarakhneorg** [comment]
A special project was written by @alexandrelombard in order to hava a library for communicating with Airsim through a socket connection: https://github.com/alexandrelombard/airsim-jvm-api

The Airsim simulator in SARL (https://github.com/alexandrelombard/sarl-airsim-interface) uses this library to be connected to Airsim.
